### ISSUE TITLE
Error "Stream map '0:s:0' matches no streams. To ignore this, add a trailing '?' to the map."

### ISSUE THREAD

**Issue by mariodac** [Montvydas/translatesubs#10]
Error in subtitle extraction, I'm using an .avi video file, below is a printout of the error

![image](https://github.com/Montvydas/translatesubs/assets/38120268/75c2a248-1f8f-4e09-a89a-c021111fbded)

**Comment by sametguzeldev** [comment]
I am having the same issue

**Comment by sametguzeldev** [comment]
It seems like your file does not contain any subtitles to me. Maybe it is burned to the video itself?
