### ISSUE TITLE
0.2.0 conflicting dependencies

### ISSUE THREAD

**Issue by 74d02** [Montvydas/translatesubs#3]
Hi,

Trying to install the newest 0.2.0 in python 3.8 gives conflicting dependencies error:

```
ERROR: Cannot install httpx==0.13.3 and translatesubs==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    translatesubs 0.2.0 depends on chardet==4.0.0
    httpx 0.13.3 depends on chardet==3.*
```
previous version unfortunately merges both languages despite no -merge arg used.

**Comment by Montvydas** [comment]
Now fixed on 0.2.1. Apparently on Python version <3.9 pip was resolving packages in a different way, thus it would be working on python 3.9 but not on versions below.
