### ISSUE TITLE
delete line after translation

### ISSUE THREAD

**Issue by joaquintadeo** [Montvydas/translatesubs#6]
Hello! is it posible to delete the line after it was translated? thanks!

**Comment by Montvydas** [comment]
Hey, can you explain a bit more?

**Comment by joaquintadeo** [comment]
So when I translate a file, I get the two lines (the translated one and the original one) I'd like to keep only the translated one and delete the original

**Comment by olivergrabinski** [comment]
You have to remove `{secondary}` from this line

```python
origin_sub.text = f'{sub.open_style}{main}{secondary}{sub.close_style}'
```

in the `update_subs` method (`subs_manager.py`).

**Comment by Montvydas** [comment]
Fixed now, I will push an updated version soon under v_0.2.3.
